a=int(input("Enter a value :"))
b=int(input("Enter b value :"))
print("Addition a & b is ",a+b)
print("Subtraction of a & b is",a-b)
print("Multiplication of a & b is ",a*b)
print("Division of a & b is ",a/b)
print("Remainder of a & b is ",a%b)
print("Exponent of a & b is ",a**b)
print("Floor division of a & b is ",a//b)
