s1=input("Enter the first string :")
s2=input("Enter the second string :")
print("First string is : ", s1)
print("Second string is : ",s2)
print("Concatenation of two strings : ",s1+s2)
print("Substring of given string : ",s1[1:4])